const feedData = [
  {
    writerId: "happy_life",
    writerImg: process.env.PUBLIC_URL + "/assets/writer1.jpeg",
    writerTxt: "반포 한강공원",
    feedImg: "/assets/feedImg1.jpeg",
    feedTxt: "오늘은 한강 나들이 다녀왔다! 날씨 너무 좋아..",
    cmtNum: 2,
    id1: "iamchulsu",
    id2: "huindung2",
    cmt1: "날씨 굿",
    cmt2: "요즘 진짜 산책하기 딱 좋은 날씨야!",
  },
  {
    writerId: "disneyl0ver",
    writerImg: process.env.PUBLIC_URL + "/assets/writer2.jpeg",
    writerTxt: "Tokyo, Disney Sea",
    feedImg: "/assets/feedImg2.jpeg",
    feedTxt: "디즈니씨 맛집 추천! 보기에도 귀엽고 맛도 맛있음",
    cmtNum: 3,
    id1: "shinzzang_01",
    id2: "happy_life",
    id3: "baby_zzanga",
    cmt1: "미키 빵 맛있겠다",
    cmt2: "디즈니씨는 빵도 맛집이야?!",
    cmt3: "디즈니 먹방 잘 보고 갑니다~ 츄릅",
  },
  {
    writerId: "japanlife2",
    writerImg: process.env.PUBLIC_URL + "/assets/writer3.jpeg",
    writerTxt: "Japan, Tokyo",
    feedImg: "/assets/feedImg3.jpeg",
    feedTxt:
      "도쿄 여행 중 아사쿠사에서 먹은 메론빵 🍈🥐 날씨 좋으니까 더 맛있넹",
    cmtNum: 3,
    id1: "user_01",
    id2: "user_02",
    id3: "user_03",
    cmt1: "역시 도쿄는 메론빵이지",
    cmt2: "일본 길빵도 맛있나요?",
    cmt3: "아사쿠사 길거리 음식이 그렇게 맛있다던데 메론빵이라니 미쳤다",
  },
  {
    writerId: "doldam_luv",
    writerImg: process.env.PUBLIC_URL + "/assets/writer4.jpeg",
    writerTxt: "Jeju Island",
    feedImg: "/assets/feedImg4.jpeg",
    feedTxt: "제주 신라호텔에서 호캉스 중 🌴 여유+힐링 최고다 서울 가기 싫다..",
    cmtNum: 3,
    id1: "comment_01",
    id2: "comment_02",
    id3: "comment_03",
    cmt1: "호캉스 부러워요",
    cmt2: "와! 제주도인데 완전 외국 같네요 힐링 제대로!",
    cmt3: "제주도 맛집도 추천해주세요!",
  },
  {
    writerId: "wannabe_camper",
    writerImg: process.env.PUBLIC_URL + "/assets/writer5.jpeg",
    writerTxt: "포천 우니메이카 캠핑장",
    feedImg: "/assets/feedImg5.jpeg",
    feedTxt: "캠핑음식 레시피 추천! 채끝 짜파구리 존맛",
    cmtNum: 2,
    id1: "camper_01",
    id2: "camper_02",
    cmt1: "맛있겠다...",
    cmt2: "헉 저도 다음 주에 캠핑 가는데 채끝 짜파구리 도전해 봐야겠어요",
  },
  {
    writerId: "cafe__yamyam",
    writerImg: process.env.PUBLIC_URL + "/assets/writer6.jpeg",
    writerTxt: "북촌 한옥마을",
    feedImg: "/assets/feedImg6.jpeg",
    feedTxt:
      "한옥마을 가운데서 발견한 크리스마스 분위기 카페 🎄 눈사람 아이스크림 너무 귀엽다",
    cmtNum: 2,
    id1: "chat_01",
    id2: "chat_02",
    cmt1: "아직도 크리스마스 분위기라니 너무 예쁜 곳이네요",
    cmt2: "눈사람 먹기 아깝겠다 ㅠㅠ",
  },
];

export default feedData;
